### ISSUE TITLE
units

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#10]
https://www.w3schools.com/css/css_units.asp

**Comment by Parissa-Parsania** [comment]
- CSS has several different units for expressing a length, such as width, margin, padding, font-size, etc. that should be followed by a length unit, such as 10px, 2em, etc.

- There are two types of length units: absolute and relative.

- Absolute length units (such as cm, px) are not recommended for use on-screen, because screen sizes vary so much.

- Relative length units (such as vh, %) specify a length relative to another length property.
The em and rem units are practical in creating a perfectly scalable layout!

- em ; Relative to the font-size of the element (2em means 2 times the size of the current font)

- rem: Relative to font-size of the root element.The rem unit sets the font-size relative to the browsers base font-size, and will not inherit from its parents.

- vh: Relative to 1% of the height of the viewport
(Viewport = the browser window size. If the viewport is 50cm wide, 1vw = 0.5cm.)

- %: Relative to the parent element. The % unit sets the font-size relative to the current font-size.
