### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#11]
https://www.w3schools.com/css/css_positioning.asp

**Comment by arashbahreini** [comment]
Read the `Image Text` part of https://www.w3schools.com/css/css3_images.asp once you will be done with this course.

**Comment by Parissa-Parsania** [comment]
Summary:
CSS Layout - The position Property: The` position` property specifies the type of positioning method used for an element (static, relative, fixed, absolute, or sticky).

- `position: static`: HTML elements are positioned static by default, they are not positioned in any special way; it is always positioned according to the normal flow of the page

- `position: relative`: Setting the top, right, bottom, and left properties of a relatively-positioned element will cause it to be adjusted away from its normal position

- `position: fixed`: element positioned relative to the viewport, which means it always stays in the same place even if the page is scrolled.

- `position: absolute`: the element is positioned relative to the nearest positioned ancestor (instead of positioned relative to the viewport, like fixed).

- `position: sticky`: The element is positioned based on the user's scroll position. A sticky element toggles between `relative` and `fixed`, depending on the scroll position. It is positioned `relative` until a given offset position is met in the viewport - then it "sticks" in place (like position: `fixed`).

- Overlapping Elements: The` z-index `property specifies the stack order of an element (which element should be placed in front of, or behind, the others).

- Positioning Text In an Image
