### ISSUE TITLE
JavaScript Array Methods

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#36]
https://www.w3schools.com/js/js_array_methods.asp

**Comment by Parissa-Parsania** [comment]
Summary:

- Converting Arrays to Strings
`toString()` converts an array to a string of (comma separated) array values
The` join() `method also joins all array elements into a string.
It behaves just like `toString()`, but in addition you can specify the separator

- Popping
The `pop() `method removes the last element from an array. it returns the value that was "popped out"

- Pushing
The `push()` method adds a new element to an array (at the end).The `push() `method returns the new array length

- Shifting Elements
Shifting is equivalent to popping, working on the first element instead of the last.
The` shift()` method removes the first array element and "shifts" all other elements to a lower index.
The `shift()` method returns the string that was "shifted out"
The `unshift()` method adds a new element to an array (at the beginning), and "unshifts" older elements.
The `unshift() `method returns the new array length.

- Changing Elements
Array elements are accessed using their index number:
Array indexes start with 0. [0] is the first array element, [1] is the second, [2] is the third ...
The length property provides an easy way to append a new element to an array:

Example
```
var fruits = ["Banana", "Orange", "Apple", "Mango"];
fruits[fruits.length] = "Kiwi";
```          // Appends "Kiwi" to fruits

- Deleting Elements
Since JavaScript arrays are objects, elements can be deleted by using the JavaScript operator `delete`
Using delete may leave undefined holes in the array. Use pop() or shift() instead.

- Splicing an Array
The `splice() `method can be used to add new items to an array.

Example
```
var fruits = ["Banana", "Orange", "Apple", "Mango"];
fruits.splice(2, 0, "Lemon", "Kiwi");
``` returns: New Array:
Banana,Orange,Lemon,Kiwi,Apple,Mango
The first parameter (2) defines the position where new elements should be added (spliced in).
The second parameter (0) defines how many elements should be removed.
The rest of the parameters ("Lemon" , "Kiwi") define the new elements to be added.
The `splice() `method returns an array with the deleted items.

- Using splice() to Remove Elements
you can use` splice()` to remove elements without leaving "holes" in the array.

- Merging (Concatenating) Arrays
The `concat() `method creates a new array by merging (concatenating) existing arrays.
does not change the existing arrays. It always returns a new array and can take any number of array arguments.

- Slicing an Array
The `slice() `method slices out a piece of an array into a new array.
This example slices out a part of an array starting from array element 1 ("Orange"):

Example
```
var fruits = ["Banana", "Orange", "Lemon", "Apple", "Mango"];
var citrus = fruits.slice(1);
``` it return: Orange,Lemon,Apple,Mango

The` slice() `method can take two arguments like slice(1, 3).
The method then selects elements from the start argument, and up to (but not including) the end argument.

- Automatic toString()

- Finding Max and Min Values in an Array, Sorting Arrays, Sorting arrays are covered in the next chapter of this tutorial.
