### ISSUE TITLE
JavaScript Math Object

### ISSUE THREAD

**Issue by arashbahreini** [arashbahreini/me-parissa#41]
https://www.w3schools.com/js/js_math.asp

**Comment by Parissa-Parsania** [comment]
Summary:
The JavaScript Math object allows you to perform mathematical tasks on numbers.

- `Math.round(x) `returns the value of x rounded to its nearest integer

- `Math.pow(x, y)` returns the value of x to the power of y

- `Math.sqrt(x)` returns the square root of x

- `Math.abs(x) `returns the absolute (positive) value of x

- `Math.ceil(x)` returns the value of x rounded up to its nearest integer

- `Math.floor(x)` returns the value of x rounded down to its nearest integer

- `Math.sin(x)` returns the sine (a value between -1 and 1) of the angle x (given in radians).

If you want to use degrees instead of radians, you have to convert degrees to radians:

Angle in radians = Angle in degrees x PI / 180

- `Math.cos(x)` returns the cosine (a value between -1 and 1) of the angle x (given in radians)

- `Math.min()` and `Math.max()` can be used to find the lowest or highest value in a list of arguments

- `Math.random()` returns a random number between 0 (inclusive), and 1 (exclusive)

- Math Properties (Constants)

- Math Object Methods
